<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTPlUUsa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTPlUUsa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTPlUUsa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTPlUUsa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTPlUUsa\App_KernelDevDebugContainer([
    'container.build_hash' => 'TPlUUsa',
    'container.build_id' => '222572e3',
    'container.build_time' => 1619367068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTPlUUsa');
