<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTuEofAe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTuEofAe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTuEofAe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTuEofAe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTuEofAe\App_KernelDevDebugContainer([
    'container.build_hash' => 'TuEofAe',
    'container.build_id' => 'd418461d',
    'container.build_time' => 1619354786,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTuEofAe');
