baseURL = "https://ies-jaume-balmes.github.io/2020-21-DAW2-M12-Recipe-Me/"
title = "Recipeme docs"
theme = "hugo-geekdoc"
publishDir = "../docs"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

# (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
geekdocMenuBundle = true