lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:        30  # Tiempo de expiracion del TOKEN

#Login 
# curl -X POST -H "Content-Type: application/json" https://localhost:8000/api/login_check -d '{"email":"frank@recipeme.com","password":"frank"}'

# Petición con TOKEN:
# curl -X POST -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImN0eSI6IkpXVCJ9.eyJpYXQiOjE2MjE5NTU4OTMsImV4cCI6MTYyMTk1NTkyMywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImZyYW5rQHJlY2lwZW1lLmNvbSIsInVzZXJJZCI6MX0.ERUf50Jlk30GLUhwxTphw8hzYW7iGCZNNlDicWj4Fg2m2oxHkw9n5kCi4dU2LtSmCoQZuAFYGxVc6C2yEqv8_iC_b0RAUrPtJ39AzT0onEpGZRYrig-F6F9Tkk4inBpF7trqW2dF3Q5eJ89A-jf3bfIHM58gs2RgHn8xdppcCNkGkpLAWNS7Z7y1zUWgsdQv-ySpB1rMV4b3-lX0cC3mOMdDdfl0NEOGX00BtWPT8R7rAd-q5c02etkYenGQGFzJiZg1pcF5_a2CUJwRe-f_z02KMUR_9NManjVUsB3MzxW_J9HTSsgB5ZXnPiJK4NOVkYycIgLKnfrei2drO0sjXg" https://localhost:8000/api/recipes

# Petición con REFRESH TOKEN:
# curl -X POST -H "Content-Type: application/json" https://localhost:8000/api/token/refresh -d '{"refresh_token":"1deb1a91dce45534c447e173ddbd4b805b9b589b2e6f2324f4f8cfe97ea89641b2bd02ee71a57c4df41dfe24529f8b9f451086c2c777e9ea0683369f1066525f"}'
